### ISSUE TITLE
Unable to complete the training Job

### ISSUE THREAD

**Issue by rishi456187** [aws-samples/finetune-deploy-bert-with-amazon-sagemaker-for-hugging-face#6]
I am trying to run the notebook as it is and getting error mentioned below, 

Traceback (most recent call last):  File "train.py", line 45, in <module>    train_dataset = load_from_disk(args.training_dir)  File "/opt/conda/lib/python3.6/site-packages/datasets/load.py", line 797, in load_from_disk    return Dataset.load_from_disk(dataset_path, fs, keep_in_memory=keep_in_memory)  File "/opt/conda/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 665, in load_from_disk    dataset_info = DatasetInfo.from_dict(json.load(dataset_info_file))  File "/opt/conda/lib/python3.6/site-packages/datasets/info.py", line 225, in from_dict    return cls(**{k: v for k, v in dataset_info_dict.items() if k in field_names})  File "<string>", line 18, in __init__  File "/opt/conda/lib/python3.6/site-packages/datasets/info.py", line 137, in __post_init__    self.features = Features.from_dict(self.features)  File "/opt/conda/lib/python3.6/site-packages/datasets/features.py", line 947, in from_dict    obj = generate_from_dict(dic)  File "/opt/conda/lib/python3.6/site-packages/datasets/features.py", line 895, in generate_from_dict    return {key: generate_from_dict(value) for key, value in obj.items()}  File "/opt/conda/lib/python3.6/site-packages/datasets/features.py", line 895, in <dictcomp>    return {key: generate_from_dict(value) for key, value in obj.items()}  File "/opt/conda/lib/python3.6/site-packages/datasets/features.py", line 899, in generate_from_dict    return Sequence(feature=generate_from_dict(obj["feature"]), length=obj["length"]) | Traceback (most recent call last): File "train.py", line 45, in <module> train_dataset = load_from_disk(args.training_dir) File "/opt/conda/lib/python3.6/site-packages/datasets/load.py", line 797, in load_from_disk return Dataset.load_from_disk(dataset_path, fs, keep_in_memory=keep_in_memory) File "/opt/conda/lib/python3.6/site-packages/datasets/arrow_dataset.py", line 665, in load_from_disk dataset_info = DatasetInfo.from_dict(json.load(dataset_info_file)) File "/opt/conda/lib/python3.6/site-packages/datasets/info.py", line 225, in from_dict return cls(**{k: v for k, v in dataset_info_dict.items() if k in field_names}) File "<string>", line 18, in __init__ File "/opt/conda/lib/python3.6/site-packages/datasets/info.py", line 137, in __post_init__ self.features = Features.from_dict(self.features) File "/opt/conda/lib/python3.6/site-packages/datasets/features.py", line 947, in from_dict obj = generate_from_dict(dic) File "/opt/conda/lib/python3.6/site-packages/datasets/features.py", line 895, in generate_from_dict return {key: generate_from_dict(value) for key, value in obj.items()} File "/opt/conda/lib/python3.6/site-packages/datasets/features.py", line 895, in <dictcomp> return {key: generate_from_dict(value) for key, value in obj.items()} File "/opt/conda/lib/python3.6/site-packages/datasets/features.py", line 899, in generate_from_dict return Sequence(feature=generate_from_dict(obj["feature"]), length=obj["length"])

KeyError: 'length'

**Comment by aditya-krish** [comment]
@rishi456187 Did you resolve this?
